development: &default
  adapter: postgresql
  encoding: unicode
  database: svd_dev
  pool: 20
  host: localhost
  port: 5432

test:
  <<: *default
  database: svd_test

production:
  <<: *default
  database: svd_prod
